# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-18 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_auto_20211011_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='state',
            field=models.CharField(choices=[('cancelled', 'Cancelled - visible to all, registration closed to all'), ('closed', 'Closed - visible to all, registration closed to all'), ('hidden', 'Hidden - hidden to all, registration closed to all'), ('open', 'Open - visible to all, registration conditionally open to all'), ('preview', 'Preview - visible only to admins, registration conditionally open only to admins')], help_text='state of league, controls visibility and whether registration is open', max_length=32),
        ),
    ]
